### ISSUE TITLE
Accept rust-toolchain.toml in workspace root

### ISSUE THREAD

**Issue by CeciliaZ030** [clechasseur/rs-cargo#117]
Feature request: automatically config toolchain based on `rust-toolchain.toml` in workspace root
actions-rs has gone deprecated, please make this compatible with the new .toml format of toolchain specification.
Propose usage:
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust toolchain
        uses: clechasseur/rs-cargo@v2
        with:
          profile: minimal
          toolchain-file: rust-toolchain.toml
          override: true
```
